(set appname "sample")
(set deus "http://deus.xmachine.io")
(set credentials "admin:xmachine")

(task "zip" is
      (SH "mkdir -p build/#{appname}.app")
      (SH "cp -r #{appname} build/#{appname}.app/#{appname}")
      (SH "cp -r public build/#{appname}.app")
      (SH "cd build; zip -r #{appname}.zip #{appname}.app"))

(task "pub" => "zip" is
      (set command (+ "curl -s " deus "/api/"
                      appname
                      " -T build/#{appname}.zip"
                      " -X POST"
                      " -u " credentials))
      (puts command)
      (set version (NSString stringWithShellCommand:command))
      (puts "app version: #{version}")
      (set command (+ "curl -s " deus "/api/"
                      appname
                      "/deploy/"
                      version
                      " -X POST"
                      " -u " credentials))
      (set result (NSString stringWithShellCommand:command))
      (puts "deployment result: #{result}"))

(task "default" => "zip")

