
(function generate-upstart-config (CONTAINER NAME PORT) <<-END
#
# AUTOMATICALLY GENERATED BY AGENTBOX
#
start on runlevel [2345]
setuid agentbox
chdir #{AGENTBOX-PATH}/workers/#{CONTAINER}/#{NAME}.app
exec ./#{NAME} -p #{PORT}
respawn
respawn limit 10 90
END)
